name: Deploy site

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '0 0 * * 3'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl --fail --request POST \
            --url https://api.github.com/repos/${{ github.repository }}/pages/builds \
            --header "Authorization: Bearer $USER_TOKEN"
        env:
          USER_TOKEN: ${{ secrets.USER_TOKEN }}
